Repository ublue-os/bazzite-dx, pull requests merged in 2025-07, with the labels that each got.

#107 chore: Update image-info and os-release
  build_files/00-image-info.sh
Labels: lgtm, size:S

#109 update image-info and os-release v2
  .github/workflows/build.yml
  Containerfile
  build_files/00-image-info.sh
Labels: size:S

#110 chore(kde): Update about page
  build_files/00-image-info.sh
Labels: lgtm, size:S

#111 feat: Simplify builds by dropping -deck and keeping gamemode
  .github/workflows/build.yml
  README.md
  build_files/20-install-apps.sh
Labels: enhancement, lgtm, size:M

#115 fix: Re-enable mutliuser menu options on KDE builds
  build_files/20-install-apps.sh
Labels: size:S

#119 feat: Add usbmuxd to installed packages for iteracting with iDevices
  build_files/20-install-apps.sh
Labels: enhancement, lgtm, size:XS
