Repository ublue-os/bazzite-dx, pull requests merged in 2025-05, with the labels that each got.

#69 fix(just): remove outdated recipe
  build_files/60-clean-base.sh
Labels: size:XS

#71 fix: sign images in merge_queue
  .github/workflows/build.yml
Labels: size:XS

#79 Fix README URL 404
  README.md
Labels: documentation, lgtm, size:XS

#86 fix: update docker extension to container extension
  system_files/usr/share/ublue-os/user-setup.hooks.d/11-vscode-extensions.sh
Labels: lgtm, size:XS
