Repository ublue-os/bazzite-dx, pull requests merged in 2025-03, with the labels that each got.

#27 chore: move from amyOS branding to Bazzite branding
  .github/workflows/build.yml
  build_files/50-fix-opt.sh
  iso.toml
  repo_files/amy-logo-black.png
  repo_files/amy-logo-white.png
  system_files/etc/ublue-os/system_flatpaks
Labels: lgtm

#29 ci: use renovate best-practices
  .github/renovate.json5
Labels: enhancement, lgtm, size:XS

#31 ci: remove the labeled gate for the `safe-to-run` tag
  .github/workflows/build.yml
Labels: lgtm, safe-to-run, size:XS

#20 ci: Implement image matrix
  .github/workflows/build.yml
Labels: size:L

#32 fix: Move env vars under step
  .github/workflows/build.yml
Labels: lgtm, size:XS

#35 feat: use static base image matrix
  .github/workflows/build.yml
Labels: enhancement, lgtm, size:M

#36 feat: Parametrize base image and fix image naming
  .github/workflows/build.yml
  Containerfile
Labels: enhancement, lgtm, size:XS

#17 fix: Assign docker group at runtime to users in the wheel group
  build_files/20-install-apps.sh
  system_files/usr/share/ublue-os/privileged-setup.hooks.d/20-dx.sh
  system_files/usr/share/ublue-os/user-setup.hooks.d/99-privileged.sh
Labels: lgtm, safe-to-run, size:M

#38 fix: Ensure image.version label is set
  .github/workflows/build.yml
Labels: bug, lgtm, size:XS

#41 fix: downgrade dnf5 due gpg bug
  build_files/20-install-apps.sh
Labels: bug, lgtm, size:XS

#39 feat: add extensions installer hook for vscode
  build_files/40-services.sh
  system_files/usr/share/ublue-os/user-setup.hooks.d/11-vscode-extensions.sh
Labels: enhancement, lgtm, size:S

#40 feat: match packagelist with rest of -dx
  build_files/20-install-apps.sh
Labels: enhancement, lgtm, size:S
