Repository ublue-os/bazzite-dx, pull requests merged in 2025-04, with the labels that each got.

#50 chore: Remove personal amyos components
  build_files/20-install-apps.sh
  build_files/60-clean-base.sh
  build_files/999-cleanup.sh
  system_files/etc/skel/.config/Code/User/settings.json
  system_files/usr/bin/gamescope-session
  system_files/usr/bin/jupiter-biosupdate
  system_files/usr/bin/steamos-polkit-helpers/jupiter-biosupdate
  system_files/usr/bin/steamos-polkit-helpers/steamos-set-timezone
  system_files/usr/bin/steamos-polkit-helpers/steamos-update
  system_files/usr/bin/steamos-select-branch
  system_files/usr/bin/steamos-session-select
  system_files/usr/bin/steamos-update
  system_files/usr/share/accounts/providers/kde/google.provider
  system_files/usr/share/wayland-sessions/steam.desktop
Labels: lgtm, size:M

#51 chore: Pull in ccache
  build_files/20-install-apps.sh
Labels: lgtm, size:XS

#52 fix: Use fallback testing packages for docker
  build_files/20-install-apps.sh
Labels: bug, lgtm, size:S

#53 fix: Add missing enable flag
  build_files/20-install-apps.sh
Labels: size:XS

#54 feat: Add Steam Gamemode session
  build_files/20-install-apps.sh
  system_files/usr/bin/bazzite-steam
Labels: enhancement, size:XS

#56 chore(ci): autobuild when bazzite updates
  .github/renovate.json5
  .github/workflows/build.yml
  image-versions.yaml
Labels: size:S

#60 fix(docker): load iptable_nat
  build_files/20-install-apps.sh
Labels: lgtm, size:XS

#65 chore(ci): attempt to fix build on merge
  .github/workflows/build.yml
Labels: size:XS

#66 fix: update image-versions.yaml
  image-versions.yaml
Labels: size:XS
